### ISSUE TITLE
Performance?

### ISSUE THREAD

**Issue by eklipse2k8** [microsoft/cppwin32#10]
What are the performance costs here? Wouldn't accessing Win32 API over winmd take a noticeable performance hit? The beauty of C++17 is that it's near-zero cost abstractions.

**Comment by kennykerr** [comment]
All of the language support we are developing use the metadata to generate code at or before compile time. This does not affect run time performance at all.

**Comment by eklipse2k8** [comment]
Oh that's pretty cool!
