### ISSUE TITLE
This library and WIL

### ISSUE THREAD

**Issue by shmuelie** [microsoft/cppwin32#7]
In many ways the [Windows Implementation Libraries](https://github.com/microsoft/wil) already provides many modern C++ APIs for Win32.

How does the two play out in the future? Merge/converge?

**Comment by kennykerr** [comment]
WIL provides wrappers for the Windows API. This project attempts to provide the actual Windows API definitions. Those are very different concerns. I could certainly imagine WIL relying on this project for those definitions, and developers using them together, but there doesn't appear to be any need to merge them.
