### ISSUE TITLE
Too long namespaces and file names

### ISSUE THREAD

**Issue by vrubleg** [microsoft/cppwin32#9]
Please consider making namespaces and file names shorter. There are too many duplicated parts. We know that it is for Windows, no any good reasons to mention it three times in every place.

For example:
```
using namespace win32;
using namespace win32::Windows::Win32;
using namespace win32::Windows::Win32::Direct3D12;
using namespace win32::Windows::Win32::SystemServices;
using namespace win32::Windows::Win32::Dxgi;
using namespace win32::Windows::Win32::Direct3D11;
```
It could look just like this:
```
using namespace Win32;
using namespace Win32::Direct3D12;
using namespace Win32::SystemServices;
using namespace Win32::DXGI;
using namespace Win32::Direct3D11;
```

Or this example:
```
#include <win32/Windows.Win32.Dxgi.h>
#include <win32/Windows.Win32.Direct3D12.h>
#include <win32/Windows.Win32.Direct3D11.h>
#include <win32/Windows.Win32.DisplayDevices.h>
#include <win32/Windows.Win32.MenusAndResources.h>
#include <win32/Windows.Win32.SystemServices.h>
#include <win32/Windows.Win32.WindowsAndMessaging.h>
```
It could look like this:
```
#include <Win32/DXGI.h>
#include <Win32/Direct3D12.h>
#include <Win32/Direct3D11.h>
#include <Win32/DisplayDevices.h>
#include <Win32/MenusAndResources.h>
#include <Win32/SystemServices.h>
#include <Win32/WindowsAndMessaging.h>
```

**Comment by kennykerr** [comment]
Hi Evgeny, the names are derived from metadata. In order to avoid collisions with any future APIs or APIs from different sources, it's important that the namespace-derived header names are unique. Today its dominated by namespaces starting with `Windows.*` but in future we are likely to see more namespaces with other root namespaces as well.

**Comment by DefaultRyan** [comment]
I'll just add that because we're getting those namespaces by consuming the output of https://github.com/microsoft/win32metadata, that would be the place to raise an issue like this.
